### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by TheThon** [autumnlikescode/0x7-Unpacker#1]
![image](https://github.com/autumnlikescode/0x7-Unpacker/assets/64498402/9a036975-7ce4-4fe2-b6ff-bf494cdfcc04)
hello i don't get an error when i try to build, but ultimately i can't
pls help 

![image](https://github.com/autumnlikescode/0x7-Unpacker/assets/64498402/0b62c0c1-16d5-4322-91f2-a2edb81cd8aa)

**Comment by autumnlikescode** [comment]
You haven't passed a module to the arguments of the application which is why its failing when debugging. Your build output shows the file already built and won't be rebuilt if you build again as its up-to-date. Check the build folder for the unpacker exe. The unpacker works by either dragging and dropping an obfuscated module onto the unpacker or by running "unpacker.exe module.exe".
